# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraTool < Formula
  desc "jt - jira-tool is a CLI tool for viewing and manipulating JIRA issues."
  homepage "https://github.com/StevenACoffman/jira-tool"
  version "0.0.6"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StevenACoffman/jira-tool/releases/download/v0.0.6/jira-tool_0.0.6_Darwin_x86_64.tar.gz"
      sha256 "299e123780908bc9ba892f09a0cc4b205eac92bfa64912b84befc3fbaeee271c"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/StevenACoffman/jira-tool/releases/download/v0.0.6/jira-tool_0.0.6_Linux_x86_64.tar.gz"
      sha256 "7ae99ce4e6673861c86802329982d36d884f3f00f86fed47eb7996f6208945d9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StevenACoffman/jira-tool/releases/download/v0.0.6/jira-tool_0.0.6_Linux_arm64.tar.gz"
      sha256 "bcdfdd126d87cab0ade38fb31a14a4c7e5a8d38746c71558526824f6c82b6749"
    end
  end

  def install
    bin.install "jt"
    ...
  end
end
