# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraTool < Formula
  desc "jt - jira-tool is a CLI tool for viewing and manipulating JIRA issues."
  homepage "https://github.com/StevenACoffman/jira-tool"
  version "0.0.3"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StevenACoffman/jira-tool/releases/download/v0.0.3/jira-tool_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "32ba972c5e98eff2892738b235bcfd60f8c546086697530bc99e6bc479d85f73"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/StevenACoffman/jira-tool/releases/download/v0.0.3/jira-tool_0.0.3_Linux_x86_64.tar.gz"
      sha256 "ad8e1f7c52fed4611e4388872504690ddb3e71e5b59f688353707196640dff9c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StevenACoffman/jira-tool/releases/download/v0.0.3/jira-tool_0.0.3_Linux_arm64.tar.gz"
      sha256 "f531ae110046505bdd54852c45474f82ec903d33b8c0ab8c970662851663a758"
    end
  end

  def install
    bin.install "jira-tool"
  end
end
