# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jt < Formula
  desc "jt is a CLI tool for viewing and manipulating JIRA issues."
  homepage "https://github.com/StevenACoffman/jt"
  version "0.0.9"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StevenACoffman/jt/releases/download/v0.0.9/jt_0.0.9_Darwin_x86_64.tar.gz"
      sha256 "fb28926e149bba8a003491b36645574221edf4b626aa75dd5ad0cce9f405b1e9"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/StevenACoffman/jt/releases/download/v0.0.9/jt_0.0.9_Linux_x86_64.tar.gz"
      sha256 "9dbf10e4731c533e631239190d6d0918757ca08036d09f0e5ac2ca4d07a0e3c4"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StevenACoffman/jt/releases/download/v0.0.9/jt_0.0.9_Linux_arm64.tar.gz"
      sha256 "b55c9177a303525cf5908fb8031261ffe198c9ed924bb55f0130084789b44579"
    end
  end

  def install
    bin.install "jt"
  end
end
