# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jt < Formula
  desc "jt is a CLI tool for viewing and manipulating JIRA issues."
  homepage "https://github.com/StevenACoffman/jt"
  version "0.0.8"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/StevenACoffman/jt/releases/download/v0.0.8/jt_0.0.8_Darwin_x86_64.tar.gz"
      sha256 "ecfc1ba52336794826c3ae25a81cba8d3f8130aae7f5f8ff0ee9f4d2af7b9e64"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/StevenACoffman/jt/releases/download/v0.0.8/jt_0.0.8_Linux_x86_64.tar.gz"
      sha256 "378d02a6bffb6147bf187a2f6e20b8d27021b19fd9bcb5df2892f0cff9670478"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/StevenACoffman/jt/releases/download/v0.0.8/jt_0.0.8_Linux_arm64.tar.gz"
      sha256 "671a7717272b1cc857b70f3efa9510bc7573e22b35591bc683d978366ba1988a"
    end
  end

  def install
    bin.install "jt"
  end
end
